version: '3.8'

services:
  trade-store:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/trade-store
    depends_on:
      - mongodb
    networks:
      - trade-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - trade-network

networks:
  trade-network:
    driver: bridge

volumes:
  mongodb_data: 