spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trade-store
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 