spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tradestore
  datasource:
    url: jdbc:postgresql://localhost:5432/tradestore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: com.tradestore.domain.model.Trade:com.tradestore.domain.model.Trade
        spring.json.trusted.packages: com.tradestore.domain.model
        spring.json.add.type.headers: true
        acks: all
        retries: 3
        retry.backoff.ms: 1000
    consumer:
      group-id: trade-store
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.tradestore.domain.model
        spring.json.type.mapping: com.tradestore.domain.model.Trade:com.tradestore.domain.model.Trade
        spring.json.add.type.headers: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.data.mongodb: DEBUG
    com.tradestore: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG 